version: 2.1

parameters:
  role-name:
    type: string
    default: "arn:aws:iam::992382483259:role/fieldeng_aws_ci_oidc_role" 
  aws-default-region:
    type: string
    default: "us-east-1"
  k8s-namespace:
    type: string
    default: "server4-sandbox"
  cluster-name:
    type: string
    default: "support-default-ng"


orbs:
  aws-cli: circleci/aws-cli@5.1.1

executors:
  ubuntu-default:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    environment:
      CLUSTER: << pipeline.parameters.cluster-name >>
      AWS_DEFAULT_REGION: << pipeline.parameters.aws-default-region >>


jobs:
  fetch-pvc-sizes:
    executor: ubuntu-default
    steps:
      - checkout
      - run:
          name: Installing kubectl and eksctl
          command: |
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

            echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client

            echo "Installing eksctl..."
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version
      - run:
          name: Write Kubeconfig
          command: |
            eksctl get clusters 
            eksctl utils write-kubeconfig --cluster=<< pipeline.parameters.cluster-name >>
            kubectl config set-context --current --namespace=<< pipeline.parameters.k8s-namespace >>
          no_output_timeout: 3h
      - run:
          name: Fetch pvc volume sizes
          command: |
              for pod in "postgresql-0:/bitnami/postgresql" "mongodb-0:/bitnami/mongodb" "redis-master-0:/data" "redis-slave-0:/data"; do
                  IFS=":" read pod_name path <<< "$pod"
                  echo "Checking disk usage for $pod_name at $path"
                  kubectl exec "$pod_name" -- df -h "$path"
                  echo "-----------------------------------"
              done
